//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaAnimales.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vaca
    {
        public string Nombre { get; set; }
        public string Sexo { get; set; }
        public string Raza { get; set; }
        public string Edad { get; set; }
        public string Tipo { get; set; }
        public string Rebaño { get; set; }
    }
}
